# Generated by Django 3.1.2 on 2020-10-22 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messagesapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='creationDate',
            new_name='creation_date',
        ),
    ]
